# Generated by Django 5.0.3 on 2024-03-31 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_post"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
